# Generated by Django 5.0.6 on 2024-06-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
